stages:
- prepare
- run

variables:
  ANSIBLE_COMMON_PARAMETERS: -v
  CI_FRAMEWORK_ARCHIVE: https://gitlab.avant-it.ru/api/v4/projects/660/repository/archive.tar.gz?sha=main

.base:
  image: docker-repository.avant-it.ru/ci-job:3.7.2
  interruptible: false
  script:
  - root_dir=$(pwd)
  - ssh-keygen -f "/root/.ssh/known_hosts" -R "gitlab.avant-it.ru"
  - ssh-keyscan -t rsa gitlab.avant-it.ru >> ~/.ssh/known_hosts &
  - ssh-keygen -f "/root/.ssh/known_hosts" -R "gitlab.chronos.mg"
  - ssh-keyscan -t rsa gitlab.chronos.mg >> ~/.ssh/known_hosts &
  
  - 'curl --header "Private-Token: ${GITLAB_API_TOKEN}" ${CI_FRAMEWORK_ARCHIVE} -o /tmp/ci.tgz -v'
  - tar -xf /tmp/ci.tgz -C /tmp
  - mv /tmp/*/ci $root_dir
  - rm -rf /tmp/*

  - mkdir artifacts
  - cd ${root_dir}/ci
  - ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook ${PLAYBOOK} ${ANSIBLE_COMMON_PARAMETERS}
  only:
  - "/^main$/"

.lint:
  extends: .base
  interruptible: true
  stage: prepare
  variables:
    PLAYBOOK: lint.yml

# .run_playbook:
#   extends: .base
#   stage: run
#   resource_group: run
#   artifacts:
#     name: "Playbook artifacts"
#     paths:
#     - artifacts/
#     expire_in: 10 minute 
#   variables:
#     PLAYBOOK: run.yml