---
 
  - name: Send notify to ls Telegram
    community.general.telegram:
      token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
      api_method: sendMessage
      api_args:
        chat_id: 5170286841
        parse_mode: html
        text: "{{ lookup('template', 'templates/main_telegram_message_template.yml.j2') }}"
        disable_web_page_preview: true
        disable_notification: true


