---

  - name: Grep chat id for local user
    shell: grep "{{ lookup('ansible.builtin.env','GITLAB_USER_ID') }}:" {{lookup('ansible.builtin.env','USERS')}} | awk '{print $2}'
    register: chat_id

  - name: Send notify to ls Telegram
    community.general.telegram:
      token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
      api_method: sendMessage
      api_args:
        chat_id: "{{ chat_id.stdout }}"
        parse_mode: html
        text: "{{ lookup('template', 'templates/main_telegram_message_template.yml.j2') }}"
        disable_web_page_preview: true
        disable_notification: true

