---
 
  - name: Print file
    shell: cat files/telegram
  
  - name: Print file path
    shell: echo {{lookup('ansible.builtin.env','USERS')}}

  - name: Grep chat id for local user
    shell: grep "{{ lookup('ansible.builtin.env','GITLAB_USER_ID') }}:" {{lookup('ansible.builtin.env','USERS')}} | awk '{print $2}'

  - name: Send notify to ls Telegram
    community.general.telegram:
      token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
      api_method: sendMessage
      api_args:
        chat_id: grep "{{ lookup('ansible.builtin.env','GITLAB_USER_ID') }}:" {{lookup('ansible.builtin.env','USERS')}} | awk '{print $2}'
        parse_mode: html
        text: "{{ lookup('template', 'templates/main_telegram_message_template.yml.j2') }}"
        disable_web_page_preview: true
        disable_notification: true


#"{{lookup('ansible.builtin.env','USERS'| from_yaml)[(lookup('ansible.builtin.env','GITLAB_USER_ID')| str)].tg_id}}"
#5170286841
#grep  "Chat_id:" {{ }} | awk '{print $2}'