---
 
  - name: Print file
    shell: cat files/telegram
  
  - name: Print env id
    shell: echo {{lookup('ansible.builtin.env','GITLAB_USER_ID')}}

  - name: Send notify to ls Telegram
    community.general.telegram:
      token: "{{ lookup('ansible.builtin.env', 'TELEGRAM_TOKEN') }}"
      api_method: sendMessage
      api_args:
        chat_id: "{{ lookup('ansible.builtin.template','files/telegram')[26] }}"
        parse_mode: html
        text: "{{ lookup('template', 'templates/main_telegram_message_template.yml.j2') }}"
        disable_web_page_preview: true
        disable_notification: true


#"{{lookup('ansible.builtin.env','USERS'| from_yaml)[lookup('ansible.builtin.env','GITLAB_USER_ID')].tg_id}}"
#5170286841